import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { nanoid } from 'nanoid';
import type { Provider, ProviderModel } from '@canvora/shared';
import { AppError, classifyProviderError } from './errors.js';
import { markSecretTest, readSecret, upsertSecret } from './secrets.js';

interface ProviderFile { providers: Provider[] }
const providerFile = (root: string) => join(root, 'providers.json');
export type ProviderInput = Omit<Provider, 'id' | 'apiKeyRef' | 'createdAt' | 'isPreset' | 'lastTestedAt' | 'lastTestStatus'> & { apiKey?: string; apiKeyRef?: string; isPreset?: boolean };

async function save(root: string, data: ProviderFile): Promise<void> { const target = providerFile(root); const temp = `${target}.${process.pid}.tmp`; await mkdir(dirname(target), { recursive: true }); await writeFile(temp, JSON.stringify(data, null, 2), 'utf8'); await rename(temp, target); }
export async function loadProviders(root: string): Promise<ProviderFile> { try { return JSON.parse(await readFile(providerFile(root), 'utf8')) as ProviderFile; } catch { return { providers: [] }; } }
export async function listProviders(root: string): Promise<Provider[]> { return (await loadProviders(root)).providers; }
export async function getProvider(root: string, id: string): Promise<Provider | undefined> { return (await loadProviders(root)).providers.find((provider) => provider.id === id); }
function validate(input: ProviderInput): void { if (!input.name?.trim()) throw new AppError('invalid-request', '服务商名称不能为空'); if (!input.baseUrl?.trim()) throw new AppError('invalid-request', 'Base URL 不能为空'); try { new URL(input.baseUrl); } catch { throw new AppError('invalid-request', 'Base URL 格式不正确'); } }
export async function createProvider(root: string, input: ProviderInput): Promise<Provider> { validate(input); const now = Date.now(); const secret = input.apiKey?.trim(); const provider: Provider = { id: nanoid(), name: input.name.trim(), protocol: input.protocol, baseUrl: input.baseUrl.replace(/\/$/, ''), apiKeyRef: '', enabled: input.enabled ?? true, models: input.models ?? [], isPreset: input.isPreset ?? false, createdAt: now }; if (secret) { const saved = await upsertSecret(root, provider.id, secret); provider.apiKeyRef = saved.id; } const data = await loadProviders(root); data.providers.push(provider); await save(root, data); return provider; }
export async function updateProvider(root: string, id: string, input: Partial<ProviderInput>): Promise<Provider | undefined> { const data = await loadProviders(root); const index = data.providers.findIndex((provider) => provider.id === id); if (index < 0) return undefined; const current = data.providers[index]; const next = { ...current, ...input, id: current.id, apiKeyRef: current.apiKeyRef, createdAt: current.createdAt, isPreset: current.isPreset } as Provider; if (input.name !== undefined || input.baseUrl !== undefined) validate({ ...next, ...(input as ProviderInput) }); if (input.apiKey?.trim()) { const secret = await upsertSecret(root, current.id, input.apiKey.trim(), current.apiKeyRef); next.apiKeyRef = secret.id; } delete (next as Partial<Provider> & { apiKey?: string }).apiKey; data.providers[index] = next; await save(root, data); return next; }
export async function removeProvider(root: string, id: string): Promise<boolean> { const data = await loadProviders(root); const before = data.providers.length; data.providers = data.providers.filter((provider) => provider.id !== id); if (data.providers.length !== before) await save(root, data); return data.providers.length !== before; }

function endpoint(provider: Provider): string { const base = provider.baseUrl.replace(/\/$/, ''); if (provider.protocol === 'openai-compatible' || provider.protocol === 'openai-images') return base.endsWith('/models') ? base : `${base}/models`; return base; }
export async function testProvider(root: string, provider: Provider, providedKey?: string): Promise<{ ok: true; message: string; models?: ProviderModel[] }> { const key = providedKey?.trim() || await readSecret(root, provider.id); if (!key) throw new AppError('invalid-key', '请先填写 API Key'); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10_000); try { const response = await fetch(endpoint(provider), { method: 'GET', headers: { Authorization: `Bearer ${key}`, Accept: 'application/json' }, signal: controller.signal }); const text = await response.text(); if (!response.ok) { const error = new Error(`${response.status} ${text.slice(0, 500)}`); throw classifyProviderError(error); } let models: ProviderModel[] | undefined; try { const payload = JSON.parse(text) as { data?: Array<{ id?: string }> }; if (Array.isArray(payload.data)) models = payload.data.filter((item) => item.id).map((item) => ({ id: item.id as string, displayName: item.id as string, capabilities: ['text'] })); } catch { /* A successful non-JSON health response still proves connectivity. */ } await markSecretTest(root, provider.id, true); const updated = await updateProvider(root, provider.id, { lastTestedAt: Date.now(), lastTestStatus: 'success' } as Partial<ProviderInput>); void updated; return { ok: true, message: '连接成功', models }; } catch (error) { await markSecretTest(root, provider.id, false); await updateProvider(root, provider.id, { lastTestedAt: Date.now(), lastTestStatus: 'failed' } as Partial<ProviderInput>); throw error instanceof AppError ? error : classifyProviderError(error); } finally { clearTimeout(timer); } }
