import { chmod, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { createCipheriv, createDecipheriv, createHash, randomBytes, scryptSync } from 'node:crypto';
import { join } from 'node:path';
import { nanoid } from 'nanoid';

interface SecretRecord { id: string; providerId: string; encrypted: string; last4: string; createdAt: number; testedAt?: number; testStatus?: 'success' | 'failed' }
interface SecretFile { version: 1; salt: string; records: SecretRecord[] }
const filePath = (root: string) => join(root, 'secrets.json');
const keyFor = (root: string, salt: Buffer) => scryptSync(process.env.CANVORA_SECRET_PASSWORD ?? `canvora:${root}`, salt, 32);

function encrypt(value: string, key: Buffer): string { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key, iv); const data = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return [iv, cipher.getAuthTag(), data].map((part) => part.toString('base64')).join('.'); }
function decrypt(value: string, key: Buffer): string { const [ivText, tagText, dataText] = value.split('.'); const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(ivText, 'base64')); decipher.setAuthTag(Buffer.from(tagText, 'base64')); return Buffer.concat([decipher.update(Buffer.from(dataText, 'base64')), decipher.final()]).toString('utf8'); }
async function load(root: string): Promise<{ file: SecretFile; key: Buffer }> { try { const file = JSON.parse(await readFile(filePath(root), 'utf8')) as SecretFile; const salt = Buffer.from(file.salt, 'base64'); return { file, key: keyFor(root, salt) }; } catch { const salt = randomBytes(16); return { file: { version: 1, salt: salt.toString('base64'), records: [] }, key: keyFor(root, salt) }; } }
async function save(root: string, file: SecretFile): Promise<void> { const target = filePath(root); const temp = `${target}.${process.pid}.tmp`; await writeFile(temp, JSON.stringify(file, null, 2), { encoding: 'utf8', mode: 0o600 }); await rename(temp, target); try { await chmod(target, 0o600); } catch { /* Windows may not support POSIX modes. */ } }

export interface SecretSummary { id: string; providerId: string; last4: string; createdAt: number; testedAt?: number; testStatus?: 'success' | 'failed' }
export async function listSecrets(root: string): Promise<SecretSummary[]> { return (await load(root)).file.records.map(({ id, providerId, last4, createdAt, testedAt, testStatus }) => ({ id, providerId, last4, createdAt, testedAt, testStatus })); }
export async function upsertSecret(root: string, providerId: string, value: string, id?: string): Promise<SecretSummary> { if (!value.trim()) throw new Error('密钥不能为空'); const loaded = await load(root); const existing = id ? loaded.file.records.find((record) => record.id === id) : loaded.file.records.find((record) => record.providerId === providerId); const record: SecretRecord = { id: existing?.id ?? nanoid(), providerId, encrypted: encrypt(value, loaded.key), last4: value.slice(-4), createdAt: existing?.createdAt ?? Date.now(), testedAt: existing?.testedAt, testStatus: existing?.testStatus }; loaded.file.records = existing ? loaded.file.records.map((item) => item.id === existing.id ? record : item) : [...loaded.file.records, record]; await save(root, loaded.file); return { id: record.id, providerId, last4: record.last4, createdAt: record.createdAt, testedAt: record.testedAt, testStatus: record.testStatus }; }
export async function removeSecret(root: string, id: string): Promise<void> { const loaded = await load(root); loaded.file.records = loaded.file.records.filter((record) => record.id !== id); await save(root, loaded.file); }
export async function readSecret(root: string, providerId: string): Promise<string | undefined> { const loaded = await load(root); const record = loaded.file.records.find((item) => item.providerId === providerId); return record ? decrypt(record.encrypted, loaded.key) : undefined; }
export async function markSecretTest(root: string, providerId: string, success: boolean): Promise<void> { const loaded = await load(root); const record = loaded.file.records.find((item) => item.providerId === providerId); if (record) { record.testedAt = Date.now(); record.testStatus = success ? 'success' : 'failed'; await save(root, loaded.file); } }
export function redactSecrets(value: unknown, secrets: readonly string[]): unknown { if (typeof value === 'string') return secrets.filter(Boolean).reduce((text, secret) => text.split(secret).join(`[已脱敏:${createHash('sha256').update(secret).digest('hex').slice(0, 8)}]`), value); if (Array.isArray(value)) return value.map((item) => redactSecrets(item, secrets)); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, /key|token|secret|authorization/i.test(key) ? '[已脱敏]' : redactSecrets(item, secrets)])); return value; }
