import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useCanvasStore } from './stores/canvas-store';
import type { CanvasNode, NodeKind, PortKind } from '@canvora/shared';

type PanelTab = '素材库' | '任务中心' | '设置';
const tools: Array<[string, string, NodeKind]> = [['选择', '↖', 'note'], ['提示词', 'T', 'prompt'], ['图片', '▣', 'image'], ['视频', '▶', 'video'], ['生图', '✦', 'generateImage'], ['生视频', '◈', 'generateVideo']];
const portKinds: Record<string, PortKind> = { prompt: 'text', text: 'text', image: 'image', video: 'video', generateImage: 'image', generateVideo: 'video', note: 'any' };

function CanvasNodeView({ node, zoom, onConnectStart }: { node: CanvasNode; zoom: number; onConnectStart: (nodeId: string, portId: string, kind: PortKind) => void }) {
  const moveNode = useCanvasStore((state) => state.moveNode); const selectNode = useCanvasStore((state) => state.selectNode); const selected = useCanvasStore((state) => state.selectedNodeId === node.id);
  const dragging = useRef(false); const origin = useRef({ x: 0, y: 0 });
  const onPointerDown = (event: React.PointerEvent) => { if ((event.target as HTMLElement).closest('.port')) return; dragging.current = true; origin.current = { x: event.clientX - node.x * zoom, y: event.clientY - node.y * zoom }; selectNode(node.id); (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); };
  const onPointerMove = (event: React.PointerEvent) => { if (dragging.current) moveNode(node.id, Math.max(0, (event.clientX - origin.current.x) / zoom), Math.max(0, (event.clientY - origin.current.y) / zoom)); };
  return <div className={`canvas-node ${selected ? 'selected' : ''}`} style={{ left: node.x, top: node.y }} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={() => { dragging.current = false; }}>
    <button className="port port-in" aria-label="输入端口" onPointerDown={(event) => event.stopPropagation()} />
    <button className="port port-out" aria-label="输出端口" onPointerDown={(event) => { event.stopPropagation(); onConnectStart(node.id, 'out', portKinds[node.kind] ?? 'any'); }} />
    <div className="node-header"><span>{node.title}</span><span className="node-kind">{portKinds[node.kind] ?? 'any'}</span></div>
    <div className="node-body">{node.kind === 'prompt' || node.kind === 'text' ? <textarea defaultValue={String(node.data.text ?? '')} placeholder="写下你的提示词…" onPointerDown={(event) => event.stopPropagation()} /> : <div className="node-placeholder"><span>{node.kind === 'image' ? '图片素材' : node.kind === 'video' ? '视频素材' : '等待输入'}</span><small>语义端口：{portKinds[node.kind] ?? '通用'}</small></div>}</div>
  </div>;
}

export function App() {
  const [dark, setDark] = useState(false); const [tab, setTab] = useState<PanelTab>('素材库'); const [timelineExpanded, setTimelineExpanded] = useState(false); const [connecting, setConnecting] = useState<{ id: string; port: string; kind: PortKind } | null>(null);
  const [pan, setPan] = useState({ x: 0, y: 0 }); const [zoom, setZoom] = useState(1); const panStart = useRef<{ x: number; y: number; px: number; py: number } | null>(null);
  const nodes = useCanvasStore((state) => state.nodes); const edges = useCanvasStore((state) => state.edges); const selectedNodeId = useCanvasStore((state) => state.selectedNodeId); const addNode = useCanvasStore((state) => state.addNode); const selectNode = useCanvasStore((state) => state.selectNode); const deleteNode = useCanvasStore((state) => state.deleteNode); const duplicateNode = useCanvasStore((state) => state.duplicateNode); const connect = useCanvasStore((state) => state.connect); const deleteEdge = useCanvasStore((state) => state.deleteEdge);
  const nodeMap = useMemo(() => new Map(nodes.map((node) => [node.id, node])), [nodes]);
  const resetView = () => { setPan({ x: 0, y: 0 }); setZoom(1); };
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.target as HTMLElement).tagName === 'TEXTAREA') return; if ((event.key === 'Delete' || event.key === 'Backspace') && selectedNodeId) deleteNode(selectedNodeId); if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'd' && selectedNodeId) { event.preventDefault(); duplicateNode(selectedNodeId); } if (event.key === 'Escape') setConnecting(null); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [deleteNode, duplicateNode, selectedNodeId]);
  const onCanvasPointerDown = useCallback((event: React.PointerEvent) => { if (event.button !== 0) return; selectNode(null); panStart.current = { x: event.clientX, y: event.clientY, px: pan.x, py: pan.y }; (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); }, [pan.x, pan.y, selectNode]);
  const onCanvasPointerMove = (event: React.PointerEvent) => { if (panStart.current) setPan({ x: panStart.current.px + event.clientX - panStart.current.x, y: panStart.current.py + event.clientY - panStart.current.y }); };
  return <div className={dark ? 'app dark' : 'app'}>
    <header className="topbar"><div className="brand"><span className="brand-mark">C</span><span>Canvora</span></div><div className="project-name">未命名项目 <span className="chevron">⌄</span></div><div className="top-actions"><button className="ghost-button">保存</button><button className="ghost-button">导出</button><button className="icon-button" onClick={() => setDark((value) => !value)}>{dark ? '☀' : '☾'}</button></div></header>
    <main className="workspace"><aside className="toolbar"><div className="toolbar-title">工具</div>{tools.map(([label, icon, kind]) => <button key={label} className="tool-button" onClick={() => addNode(kind)}><span className="tool-icon">{icon}</span><span>{label}</span></button>)}<div className="toolbar-spacer"/><button className="tool-button" onClick={() => setTab('设置')}><span className="tool-icon">⚙</span><span>设置</span></button></aside>
      <section className="canvas-shell"><div className="canvas-toolbar"><span className="canvas-title">画布</span><span className="canvas-hint">拖拽空白处平移 · 滚轮缩放 · 端口连线</span><button className="zoom-button" onClick={() => setZoom((value) => Math.min(2.5, value + .1))}>＋</button><span className="zoom-label">{Math.round(zoom * 100)}%</span><button className="zoom-button" onClick={() => setZoom((value) => Math.max(.35, value - .1))}>－</button><button className="zoom-button" onClick={resetView}>重置</button></div>
        <div className="canvas-area" onPointerDown={onCanvasPointerDown} onPointerMove={onCanvasPointerMove} onPointerUp={() => { panStart.current = null; }} onWheel={(event) => { event.preventDefault(); setZoom((value) => Math.min(2.5, Math.max(.35, value * (event.deltaY > 0 ? .92 : 1.08)))); }}>
          <div className="grid" style={{ backgroundPosition: `${pan.x}px ${pan.y}px`, backgroundSize: `${24 * zoom}px ${24 * zoom}px` }} /><div className="canvas-content" style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})` }}>
            <svg className="edges-layer">{edges.map((edge) => { const from = nodeMap.get(edge.fromNodeId); const to = nodeMap.get(edge.toNodeId); if (!from || !to) return null; return <g key={edge.id} className="edge-group" onDoubleClick={(event) => { event.stopPropagation(); deleteEdge(edge.id); }}><path d={`M ${from.x + from.width} ${from.y + 70} C ${from.x + from.width + 70} ${from.y + 70}, ${to.x - 70} ${to.y + 70}, ${to.x} ${to.y + 70}`} /><text x={(from.x + from.width + to.x) / 2} y={(from.y + to.y) / 2 + 60}>{edge.kind}</text></g>; })}</svg>
            {nodes.length === 0 ? <div className="empty-canvas"><div className="empty-icon">✦</div><h2>开始你的创作</h2><p>从左侧添加节点，或把桌面上的图片、视频拖到这里</p><button className="primary-button" onClick={() => addNode('prompt')}>添加提示词节点</button></div> : <div className="node-layer">{nodes.map((node) => <CanvasNodeView key={node.id} node={node} zoom={zoom} onConnectStart={(id, port, kind) => setConnecting({ id, port, kind })} />)}</div>}
          </div>
          {connecting && <div className="connection-hint">正在连接「{connecting.kind}」端口，请点击下游节点输入端口</div>}
          {connecting && nodes.map((node) => node.id !== connecting.id ? <button key={node.id} className="connect-target" style={{ left: pan.x + (node.x) * zoom, top: pan.y + (node.y + 70) * zoom }} onClick={() => { connect(connecting.id, connecting.port, node.id, 'in', connecting.kind); setConnecting(null); }}>{node.title} 输入</button> : null)}
        </div></section>
      <aside className="right-panel"><div className="panel-tabs">{(['素材库', '任务中心', '设置'] as PanelTab[]).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div><div className="panel-content">{tab === '素材库' && <><div className="panel-heading"><span>当前项目</span><button className="small-button">导入</button></div><div className="library-empty"><div className="library-icon">▧</div><p>还没有素材</p><span>导入图片或视频后会显示在这里</span></div></>}{tab === '任务中心' && <div className="panel-section"><h3>生成任务</h3><div className="task-card"><span className="status-dot" />暂无运行中的任务</div><p className="muted">节点生成、放大和补帧任务会显示在这里。</p></div>}{tab === '设置' && <div className="panel-section"><h3>工作区设置</h3><label>项目名称<input defaultValue="未命名项目" /></label><label>主题<select defaultValue={dark ? 'dark' : 'light'}><option value="light">浅色</option><option value="dark">深色</option></select></label><button className="primary-button" onClick={() => setDark((value) => !value)}>切换主题</button></div>}</div></aside>
    </main>
    <footer className={`timeline ${timelineExpanded ? 'expanded' : ''}`}><div className="timeline-header"><span>时间轴</span><span className="muted">序列 · 视频轨道</span><button className="small-button" onClick={() => setTimelineExpanded((value) => !value)}>{timelineExpanded ? '收起' : '展开'}</button></div><div className="timeline-body"><div className="ruler"><span>00:00</span><span>00:05</span><span>00:10</span><span>00:15</span></div><div className="track-row"><div className="track-label">视频轨 1</div><div className="track-line"><div className="drop-label">把画布上的视频拖到这里</div></div></div><div className="track-row"><div className="track-label">贴图轨 1</div><div className="track-line secondary" /></div></div></footer>
  </div>;
}
